from __future__ import annotations

from typing import Protocol

from apps.api.app.domain.workbench.entities import PlatformEvent, PlatformMetricSnapshot


class LivePlatformAdapter(Protocol):
    def start_stream(self, session_id: str) -> dict: ...
    def stop_stream(self, session_id: str) -> dict: ...
    def send_comment(self, session_id: str, text: str) -> dict: ...
    def get_comment(self, session_id: str) -> list[PlatformEvent]: ...
    def get_order(self, session_id: str) -> list[PlatformEvent]: ...
    def get_metrics(self, session_id: str) -> PlatformMetricSnapshot: ...
