from __future__ import annotations

from pathlib import Path
from typing import Protocol

from apps.api.app.domain.live.entities import LiveRoomEventRecord, LiveRoomSession, SpeechArtifact


class LiveSessionRepository(Protocol):
    def save_session(self, session: LiveRoomSession) -> None: ...
    def get_session(self, session_id: str) -> LiveRoomSession: ...
    def append_event(self, session_id: str, event_type: str, payload: dict) -> LiveRoomEventRecord: ...
    def events(self, session_id: str) -> list[LiveRoomEventRecord]: ...


class SpeechArtifactRepository(Protocol):
    def save_speech_artifact(self, speech: SpeechArtifact) -> None: ...
    def get_speech_artifact(self, session_id: str, artifact_id: str) -> SpeechArtifact: ...
    def speech_audio_path(self, session_id: str, artifact_id: str) -> Path: ...
