chat_model:
  init_args:
    model: gpt-5.5
    model_provider: xinshu
    api_key:  # 留空则使用 OPENAI_API_KEY
    base_url: https://gpt.xinshu.ai
  # 聊天模型 API 调用限流
  # 设置为 null 可关闭该服务的限流
  max_requests_per_minute: null
  max_requests_per_day: null


image_generator:
  class_path: tools.ImageGeneratorNanobananaGoogleAPI
  init_args:
    api_key:
  # 图像生成 API 调用限流
  # 设置为 null 可关闭该服务的限流
  max_requests_per_minute: 2
  max_requests_per_day: 50


video_generator:
  class_path: tools.VideoGeneratorVeoGoogleAPI
  init_args:
    api_key:
  # 视频生成 API 调用限流
  # 设置为 null 可关闭该服务的限流
  max_requests_per_minute: 2
  max_requests_per_day: 50


working_dir: .working_dir/script2video
